### PR TITLE
I would like to gracefully close the sockets in m2node.

### PR DESCRIPTION
**Pull request by dinedal**
m2node.run() now returns the handler it creates. This is so that later the sockets can be closed gracefully with:

```
handler.pullSocket.close();
handler.pubSocket.close();
```

If you think there is a better way to handle this, please let me know and I'll make the needed changes.

### CODE REVIEW

**Comment by dinedal** [comment]
I've also fixed an issue where when data is not a buffer but a string, unicode characters are treated as having incorrect length (A unicode char is character length 1, but byte length 2. This causes the buffer to be under allocated)

**Comment by dan-manges** [comment]
I merged 566d1ac, looking into 2209a81 now. Thanks for the pull requests, I gave you a shoutout on twitter. https://twitter.com/#!/dan_manges/status/87581092688822272

**Comment by dinedal** [comment]
Thanks for the shoutout!

The other one I believe is rooted in express/connect. With the normal
HTTP(S) server, you get a buffer on a data event, but with express/connect
you get a string. A length on a string is character, not byte length. For
ASCII strings, this is the same number, for Unicode, it isn't. Since a
buffer is only as big as it's length, the result is that for every unicode
character in the response you lose a character off of the response's end. My
patch ensures that data is always a buffer before the length is measured.

**Comment by dinedal** [comment]
Correction: The chunk emitted on data is always a string, so it always needs
to be made into a buffer for the proper byte length. Not express/connect's
fault at all: http://nodejs.org/docs/v0.4.9/api/http.html#event_data_

**Comment by dan-manges** [comment]
Merged both commits and released as 0.1.2. Thanks again.

**Pull request merged**
